images:
  compressed : True

device:
  gpu : False

quality:
  anomaly: False
  brix: True
  color: True
  size: True

topics:
  image_topic : "/camera/color/image_raw/compressed"
  depth_topic : "/camera/aligned_depth_to_color/image_raw"
  bboxes_topic : "/BBoxes"
  output_topic : "/Qem_out"
